### PR TITLE
Update to julia 1.10

### PR DESCRIPTION
**Pull request by bgeihe**

### CODE REVIEW

**Comment by bgeihe** [comment]
Fortunately fixes #152 

But has some issue with PackageCompiler
```
- PackageCompiler: compiling fresh sysimage (incremental=false)
error during bootstrap:
LoadError("/tmp/jl_HeuRo1/sysimage_packagecompiler_47e340e8-ae21-11ee-2456-a7170323e6fe.jl", 18, LoadError("/opt/hostedtoolcache/julia/1.10.0/x64/share/julia/stdlib/v1.10/Test/src/Test.jl", 3, LoadError("/opt/hostedtoolcache/julia/1.10.0/x64/share/julia/stdlib/v1.10/Test/src/precompile.jl", 1, MethodError(Base.RedirectStdStream(1, true), (Core.CoreSTDOUT(),), 0x0000000000008634))))
```

**Comment by bgeihe** [comment]
So, we could matrix-test with Julia versions 1.9.3 (which does not fall victim to #152) and with 1.10.*. Coverage would only be tested with either of them. Still it would be nice to have PackageCompiler working with 1.10. Any ideas @sloede ?

**Comment by bgeihe** [comment]
I would like to have green lights on main again. So, for the time being, I would like to use julia 1.10 as default, and 1.9.3 for test package compiler.

**Review by sloede — CHANGES_REQUESTED** [review]
Instead of guarding all these PC.jl runs against usage with v1.10 in the if conditions, why don't you just remove the `package-compiler` from the test matrix in line 35 (https://github.com/trixi-framework/libtrixi/pull/156/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR35)? Shouldn't this then do exactly what you want: run the default items in the test matrix _except_ for the PC.jl stuff, which you explicitly add for Julia v1.9.3 in the `include` section. Or am I missing something?

**Comment by bgeihe** [comment]
Yeah, that is way more clever!

**Review by sloede — APPROVED** [review]

**Pull request merged**
