### PR TITLE
Embedding julia with mpi

### PR DESCRIPTION
**Pull request by sloede**
I don't plan to merge it, I just wanted to check what has changed in this PR 😊

### CODE REVIEW

**Comment by sloede** [comment]
Ah, so many merge conflicts 🙀

**Comment by bgeihe** [comment]
Sorry for that. My intention was not to ever merge something back from this branch. It is merely a stripped minimal example that I wanted somewhere to be stored.

**Comment by sloede** [comment]
Closing this since we will never merge that branch, and the underlying issues that motivated this PR have been fixed elsewhere.

**Comment by sloede** [comment]
@bgeihe feel free to delete the `embedding_julia...` branch once you do not need it anymore

**Pull request closed without merging**
